# Generated by Django 6.0.4 on 2026-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
